CHANGELOG.md, pubspec.yaml
I have checked out the code, ran `pub get` and `pub run test` and it passed fine.
=> Include latest intl versions

.gitignore, CHANGELOG.md, README.md, analysis_options.yaml, example/index.html, example/main.dart, lib/src/i18/messages_all.dart, lib/timeago.dart, pubspec.yaml, test/all_test.dart
Closes https://github.com/andresaraujo/timeago.dart/issues/4
=> Refactor for v1

lib/src/i18/messages_all.dart, lib/src/i18/zh_CN_messages.dart, lib/src/i18/zh_messages.dart
Add message files to i18 to support Traditional Chinese and Simplified Chinese.
=> Support languages Traditional Chinese and Simplified Chinese

example/index.html, lib/src/i18/messages_all.dart, lib/src/i18/pt_BR_messages.dart, lib/src/i18/pt_BR_short_messages.dart
=> Add Brazilian Portuguese translations

example/index.html, lib/src/i18/fa_messages.dart, lib/src/i18/messages_all.dart, lib/src/i18/messages_all_non_deferred.dart, test/all_test.dart
Hi,
I've added Farsi translation. Please let me know if it needs any changes.
=> Added Farsi translation

timeago/lib/src/messages/nl_messages.dart, timeago/lib/timeago.dart
I've added the dutch translations to the library.
=> Added dutch translations

timeago/example/index.html, timeago/example/main.dart, timeago/lib/src/messages/id_messages.dart, timeago/lib/timeago.dart
I have added Indonesian translation. Also I added example and added return type for `timeUntil()` used in example.
=> Add Indonesian translation

timeago/lib/src/messages/pl_messages.dart
=> Created polish version

timeago/lib/src/timeago.dart
Added mapping of translation pt_br that was not working when trying to set manually.
=> Mapping of the translation pt_br

timeago/lib/src/messages/ko_messages.dart, timeago/lib/timeago.dart
Added messages for korean.
Best Regards.
=> Added messages for korean

timeago/lib/src/messages/ar_messages.dart
I use this amazing package in my production app but I noticed that Arabic wording is not accurate. In Arabic we have different time words for singular, couple and plural(more than one word for plural). so this was my fix .
=> Fix Arabic wording

timeago/lib/src/messages/ru_messages.dart
Thank you for the library, I want to correct russian translate and make your package better
=> Update russian language

timeago/example/main.dart, timeago/lib/src/messages/nn_no_messages.dart, timeago/lib/timeago.dart, timeago_flutter/example/lib/main.dart
Added support for Norwegian Nynorsk (nn_NO), also fixed some shortcomings with Norwegian Bokmål in the examples
=> Norwegian Nynorsk (nn_no) support

timeago/lib/src/messages/ro_messages.dart, timeago_flutter/example/lib/main.dart
Please can you review my changes and include this Romanian language in master?
Thank you very much.
=> romanian support

timeago/lib/src/messages/es_messages.dart
In Spanish "Días" must give an accent
=> Update fix orthography fault

timeago/lib/src/messages/dv_messages.dart, timeago/lib/timeago.dart
added initial dhvehi support,might add further improvements later
=> Added dhivehi support

timeago/lib/src/messages/az_messages.dart, timeago/lib/timeago.dart
Added Azerbaijan Language and Azerbaijan short language
=> Add Azerbaijan languages - code (az)

timeago_flutter/CHANGELOG.md, timeago_flutter/README.md, timeago_flutter/example/pubspec.lock, timeago_flutter/lib/src/timer_refresh.dart, timeago_flutter/lib/src/timer_refresh_widget.dart, timeago_flutter/pubspec.yaml
Preparing files for a new release timeago\_flutter 0.3.0
=> timeago_flutter v0.3.0

timeago/example/main.dart, timeago/lib/src/messages/hi_messages.dart, timeago/lib/src/messages/ms_my_messages.dart
=> Hindi example

timeago/lib/src/messages/vi_messages.dart
=> fixed `lessThanOneMinute` label

.github/workflows/build.yml, timeago/CHANGELOG.md, timeago/lib/src/messages/en_messages.dart, timeago/lib/src/timeago.dart, timeago/pubspec.yaml, timeago/test/all_test.dart
This PR tracks all the work related to the null safety migration and the breaking changes for v3
- Updates GH action to use dev sdk
- Removes null assertions not longer needed in null safe world
- Updates english short locale to make it consistent with other libraries
=> WIP Null safety V3

timeago/lib/src/messages/ar_messages.dart
Specifically fix issues with 'from now' translations
(please squash while merging)
=> Fix and improve Arabic translations

timeago/lib/src/messages/rw_messages.dart, timeago/lib/timeago.dart, timeago_flutter/example/pubspec.lock, timeago_flutter/pubspec.lock
I've been working with this awesome package in my native language (Kinyarwanda) and i thought i might be able to help someone who might need it in future by adding Kinyarwanda messages.
=> Added Kinyarwanda language messages

timeago/lib/src/messages/hu_messages.dart
This PR adds Hungarian Messages. I'd greatly appreciate if the maintainer adds this PR to the Hacktoberfest 2021.
=> Add Hungarian messages

timeago/example/index.html, timeago/example/main.dart, timeago/lib/src/messages/fi_messages.dart, timeago/lib/timeago.dart, timeago_flutter/example/lib/main.dart
Add Finnish translation, thanks to @tlindi who made those translations
=> Add Finnish translation, thank you @tlindi

timeago/example/index.html, timeago/example/main.dart, timeago/lib/src/messages/et_messages.dart, timeago/lib/src/timeago.dart, timeago/lib/timeago.dart
Simple basic translation based on PR #160 from @LiisiKerik.
=> Add Estonian translation for messages and short messages.

.github/workflows/ghpages.yml
=> Add baseHref to gh-page action

packages/timeago/lib/src/messages/ko_messages.dart
I found a small part that needs correction.
Thanks for your package!
=> remove space in korean minutes

packages/timeago/example/index.html, packages/timeago/example/main.dart, packages/timeago/lib/src/messages/tk_messages.dart, packages/timeago/lib/timeago.dart
Hi. Could you merge this as soon as possible.
=> added Turkmen locale

packages/timeago/lib/src/messages/ar_messages.dart
examples:
منذ حوالي شهر => منذ شهر تقريباً
منذ قبل سنة => منذ سنة تقريباً
منذ منذ شهرين => منذ شهرين
منذ منذ سنتين => منذ سنتين
=> Fix words duplicates in ar language

packages/timeago/lib/src/messages/my_messages.dart, packages/timeago/pubspec.yaml
I added intl package and MyMessages dart file for Myanmar language ([Burmese language](https://en.wikipedia.org/wiki/Burmese_language)).
=> Added time ago messages for Myanmar language.

packages/timeago/lib/src/messages/ko_messages.dart
Changed awkward korean expression (조금 -> 방금)
=> fixed KoMessage awkward expression (lessThanOneMinute)

packages/timeago/example/main.dart, packages/timeago/lib/src/messages/bn_messages.dart, packages/timeago/lib/timeago.dart, packages/timeago_flutter_example/lib/main.dart
added support for the Bengali language
=> feat: added bangla (bengali) messages

packages/timeago/lib/src/messages/hu_messages.dart
References:
https://www.arcanum.com/hu/online-kiadvanyok/Lexikonok-a-magyar-nyelv-ertelmezo-szotara-1BE8B/e-e-2529E/ezelott-28E0D/
https://e-nyelv.hu/2013-01-26/ezazelottutan/
=> Fix grammar in hu_messages.dart

packages/timeago/pubspec.yaml, packages/timeago_flutter/pubspec.lock, packages/timeago_flutter_example/pubspec.lock
=> Make timeago compatible with intl 0.18.0, 0.19.0, and 0.20.0
