- timeago/CHANGELOG.md
- timeago/analysis_options.yaml
- timeago/lib/src/messages/lookupmessages.dart
- timeago/lib/src/timeago.dart
- timeago/pubspec.yaml
This PR also disables `implicit-casts` since that is quite dangerous in dart 2.0.0 and makes the necessary changes for it.
I have also done some slight cleanup to the docs, I hope that's OK.
> Add return type to format()

- timeago/lib/src/messages/pt_br_messages.dart
Add capital letter to the start of the prefixAgo() and add a suffixAgo() to the pt_br messages.
> Change pt_br preffix and suffix

- timeago/lib/src/messages/nl_messages.dart
For NL messages, suffixAgo() is "geleden" but it also appears at the end of lessThanOneMinute() causing semantically incorrect messages like "een moment geleden geleden" (one moment ago ago). This change removes "geleden" from lessThanOneMinute().
> Removed "geleden" suffix from in NL messages

- timeago/lib/src/messages/pt_br_messages.dart
Correcting portuguese language error. You can't have both the prefix and the suffix in brazilian portuguese, it's a redundancy.
Via: https://exame.abril.com.br/carreira/ha-dez-anos-atras-ou-dez-anos-atras-qual-e-o-certo/
> Correcting brazilian portuguese redundancy

- timeago/lib/src/messages/zh_cn_messages.dart
- timeago/lib/src/messages/zh_messages.dart
- Remove `prefixFromNow` from messages
- The same as [rmm5t/jquery-timeago](https://github.com/rmm5t/jquery-timeago/blob/master/locales/jquery.timeago.zh-CN.js#L13)
- Remove duplicated `suffixAgo` in `aboutAMinute`
> Correct zh messages

- timeago/lib/src/messages/pl_messages.dart
Hi,
Current Polish rules are too simple and yield invalid translations for a few numerals - I've provided an improved ruleset based on the [gettext's plural forms](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html).
Thanks! :-)
> Improve Polish messages

- timeago/lib/src/messages/fr_messages.dart
To reduce the message output length, I created a short version of the French messages removing 'environ' word everywhere because it's not an important word when you want a relative date string
> Add short French messages

- timeago_flutter/CHANGELOG.md
- timeago_flutter/pubspec.yaml
Making flutter\_timeago compatible with all timeago 2.x.x
> Making flutter_timeago compatible with all timeago 2.x.x

- timeago/lib/src/messages/pt_br_messages.dart
In Portuguese, the use of numeral in this case is more usual.
> Updated Portuguese messages

- timeago_flutter/lib/timeago_flutter.dart
- timeago_flutter/test/timeago_flutter_test.dart
- Fixes a typo in docs
- Adjusts code formatting for tests so that it's compatible with `dartfmt` and more readable
> Fix typo in docs and tests formatting

- timeago/lib/src/timeago.dart
- timeago/pubspec.yaml
See https://dart.dev/null-safety/migration-guide
all tests work
Edit: tests are failing on GH because this change requires the beta version of the Dart SDK. That's the reason why this change should be published as a pre-release version (See https://dart.dev/null-safety/migration-guide#package-version)
> Migrated to null safety

- timeago/lib/src/messages/en_messages.dart
- timeago/test/all_test.dart
This applies three changes to en_short:
1. Removes spaces between numbers and units, so that "1 h" becomes "1h"
2. Shortens "min" to "m", so that "1 min" becomes "1m" (month remains as "mo")
2. Shortens "yr" to "y", so that "1 yr" becomes "1y"
I made these changes because this is what I've witnessed to be the standard on the rest of internet:
Facebook:
Twitter:
LinkedIn:
Venmo:
Feel free to reject some or all changes if this doesn't match with the direction you want, I'll be happy to revert individual parts.
> Make en_short consistent with other sites

- timeago/lib/src/messages/ro_messages.dart
'ora' is the definitive of 'oră' - hour, and effectively translates to 'the hour'. It's incorrect to say 'o ora' because the definiteness doesn't match. It's comparable to saying 'an the hour' in English.
> Fixing mistakes [RO]

- timeago/lib/src/messages/pl_messages.dart
'około' takes the genitive form of a noun, not the accusative, and temu follows the words instead of preceding, so the case change stays. We should be saying 'około minuty temu', 'około godziny temu', 'około miesiąca temu' or 'około roku temu'.
> Fixing mistakes [PL]

- timeago/lib/src/messages/sv_messages.dart
The Swedish short messages were basically the same as the long messages so I fixed this. I also changed the abbreviation of months to _mån_ not _må_ because this is how you do it in Swedish.
> Update Swedish short messages

- timeago/lib/src/messages/pt_br_messages.dart
The `prefixAgo` string was incorrectly cased. The project default seems to be all lower cases.
Fixes #150.
> Fix casing of pt_BR messages

- timeago/lib/src/messages/ja_messages.dart
I changes some Japanese wordings.
In Japan, the word "1分未満" itself is correct, but the words "1分未満前"(`lessThanOneMinute + suffixAgo`) and "1分未満後"(`lessThanOneMinute + suffixFromNow `) are unnatural.
So I changed to use "秒" a unit that expresses time finer than minutes.
"${minutes}秒前" and "${minutes}秒後" are very natural.
I noticed that existing Japanese messages contains unnecessary "約" a word that correspond to "about" in English.
And I removed "約" from fields not containing "about".
> Update Japanese Messages

- packages/timeago/lib/src/messages/ko_messages.dart
The word '방금' is used only in the Past tense. So i changed the word with seconds, and added prefixFromNow '지금부터'. Then it more sound natural. 
*for Korean*
'방금'이 미래 시점에 쓰이면 어색하기 때문에 과거/미래 시점에 중립적인 '{seconds}초' 의 형태로 변경하였습니다. 그리고 prefix '지금부터'를 추가해 몇 초 전인지, 몇 초 후인지 구분되게 했습니다.
> Word Correction as Korean Past&Future Tense

- packages/timeago/lib/src/messages/ko_messages.dart
`'${minutes} 분';` should be `'${minutes}분';`
> Fix typo with minutes in Korean

- README.md
Due to presence of http url, we are yet to get 5 points more, so converted http url to https.
Generally I have seen organisations prefer the score of 130.
> update url from http to https

- packages/timeago/lib/src/messages/hi_messages.dart
Both "पहले" and "पूर्व" are used for "ago" word, but they where showing two times
Example:
for "a day ago", "एक दिन पहले पूर्व" is wrong,
it should be "एक दिन पूर्व" or "एक दिन पहले"
> Removed "पहले" becouse it's alternative word is already present in prefix as "पूर्व"

- packages/timeago/example/index.html
- packages/timeago/example/main.dart
- packages/timeago/lib/src/messages/tr_messages.dart
- packages/timeago_flutter_example/lib/main.dart
The abbreviation support for the Turkish language was missing, I added it.
> Shortening support for Turkish

- pubspec.yaml
Addressing CI issue like this: https://github.com/andresaraujo/timeago.dart/actions/runs/5440476799/job/14726544394
As said in the error description Melos requires to have a separate pubspec file where Melos version is specified.
> Create pubspec.yaml for Melos

- packages/timeago/lib/src/messages/pt_br_messages.dart
Improve the pt_br messages:
* The `about*` methods strings didn't convey the "about" semantics
* Using word numerals instead of numeral digits for long messages
> Improve pt_br messages

- packages/timeago/pubspec.yaml
- packages/timeago_flutter/pubspec.lock
- packages/timeago_flutter_example/pubspec.lock
Addressing comment left on: https://github.com/andresaraujo/timeago.dart/pull/220 so that this library can support two different versions of intl.
> Make timeago compatible with intl 0.18.0 and 0.19.0
